export const deleteHistoryData = [
  {
    deletionId: "DEL-2026-00452",
    itemName: "Investigation Report",
    itemType: "Report",
    recordId: "RPT-88521",
    module: "Reports",
    caseId: "CASE-1024",
    investigationId: "INV-5687",
    deletedDate: "10 Aug 2026",
    deletedTime: "11:30 AM",
    deletedBy: "Admin User",
    deletionReason: "No Longer Required",
    status: "Restore Available",
    retentionDeadline: "10 Sep 2026",
    approvalRequired: false
  },
  {
    deletionId: "DEL-2026-00451",
    itemName: "Digital Evidence File",
    itemType: "Evidence",
    recordId: "EVI-33491",
    module: "Digital Evidence",
    caseId: "CASE-1024",
    investigationId: "INV-5687",
    deletedDate: "10 Aug 2026",
    deletedTime: "11:10 AM",
    deletedBy: "Investigator",
    deletionReason: "Duplicate Record",
    status: "Restore Available",
    retentionDeadline: "10 Sep 2026",
    approvalRequired: false
  },
  {
    deletionId: "DEL-2026-00450",
    itemName: "CDR Search Record",
    itemType: "CDR",
    recordId: "CDR-99120",
    module: "CDR Investigation",
    caseId: "CASE-1024",
    investigationId: "INV-5687",
    deletedDate: "10 Aug 2026",
    deletedTime: "10:52 AM",
    deletedBy: "Investigator",
    deletionReason: "Cleanup",
    status: "Deleted",
    retentionDeadline: "10 Sep 2026",
    approvalRequired: false
  },
  {
    deletionId: "DEL-2026-00449",
    itemName: "Case Attachment",
    itemType: "Document",
    recordId: "DOC-11204",
    module: "Case Management",
    caseId: "CASE-0987",
    investigationId: "INV-5580",
    deletedDate: "10 Aug 2026",
    deletedTime: "10:30 AM",
    deletedBy: "Case Officer",
    deletionReason: "Expired Record",
    status: "Permanent Deletion Requested",
    retentionDeadline: "10 Aug 2026",
    approvalRequired: true,
    approvalStatus: "Pending",
    requestedBy: "Case Officer"
  },
  {
    deletionId: "DEL-2026-00448",
    itemName: "Data Export",
    itemType: "Export",
    recordId: "EXP-5532",
    module: "Data Management",
    caseId: "CASE-0987",
    investigationId: "INV-5580",
    deletedDate: "09 Aug 2026",
    deletedTime: "04:15 PM",
    deletedBy: "Admin User",
    deletionReason: "Data retention policy",
    status: "Permanently Deleted",
    retentionDeadline: "09 Aug 2026",
    approvalRequired: true,
    approvalStatus: "Approved",
    requestedBy: "Admin User",
    approvedBy: "System Administrator",
    approvalDate: "09 Aug 2026"
  },
  {
    deletionId: "DEL-2026-00447",
    itemName: "Communication Record",
    itemType: "Transcript",
    recordId: "COM-7741",
    module: "Communications",
    caseId: "CASE-1102",
    investigationId: "INV-5890",
    deletedDate: "08 Aug 2026",
    deletedTime: "09:20 AM",
    deletedBy: "Investigator",
    deletionReason: "Error in transcription",
    status: "Restored",
    retentionDeadline: "08 Sep 2026",
    approvalRequired: false,
    restoredBy: "Investigator",
    restoreDate: "08 Aug 2026, 10:15 AM",
    restoreReason: "Needed for cross-reference"
  },
  {
    deletionId: "DEL-2026-00446",
    itemName: "Intelligence Report",
    itemType: "Report",
    recordId: "INT-8833",
    module: "Intelligence",
    caseId: "CASE-1155",
    investigationId: "INV-6002",
    deletedDate: "05 Aug 2026",
    deletedTime: "02:45 PM",
    deletedBy: "Intelligence Officer",
    deletionReason: "Superseded by V2",
    status: "Restore Requested",
    retentionDeadline: "05 Sep 2026",
    approvalRequired: true,
    approvalStatus: "Pending"
  },
  {
    deletionId: "DEL-2026-00445",
    itemName: "Surveillance Footage",
    itemType: "Video",
    recordId: "VID-4490",
    module: "Digital Evidence",
    caseId: "CASE-1088",
    investigationId: "INV-5712",
    deletedDate: "01 Aug 2026",
    deletedTime: "11:00 AM",
    deletedBy: "Case Officer",
    deletionReason: "Storage constraints",
    status: "Deletion Failed",
    retentionDeadline: "01 Sep 2026",
    approvalRequired: false
  }
];

export const summaryStats = {
  deleted: 128,
  restoreAvailable: 42,
  restoreRequested: 7,
  restored: 19,
  permanentDeletionRequested: 8,
  permanentlyDeleted: 52,
  deletionFailed: 2
};
